name: auto-generate-gitbook
on:                                 
  push:
    branches:
    - master

jobs:
  master-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout master
      uses: actions/checkout@v2
      with:
        ref: master
            
    - name: install nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: update npm
      run: |
        npm install -g npm@latest
      
    - name: configure gitbook
      run: |
        npm install -g gitbook-cli 
        sed -i '62,64d' /opt/hostedtoolcache/node/16.2.0/x64/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js
        npm install gitbook-plugin-hide-element
        npm install gitbook-plugin-mygitalk
        npm install gitbook-plugin-page-footer-ex
        npm install gitbook-plugin-extra-html
                
    - name: generate _book folder
      run: |
        gitbook build
                
    - name: push _book to branch gh-pages 
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/${{github.repository}}
        MYEMAIL: 3354794846@qq.com                 
        MYNAME: ${{github.repository_owner}}          
      run: |
        cd _book
        git config --global user.email "${MYEMAIL}"
        git config --global user.name "${MYNAME}"
        git init
        git remote add origin https://${REF}
        git add . 
        git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
        git branch -M master
        git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages
